//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyExchanger
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurrencyExchanger()
        {
            this.Services = new HashSet<Service>();
            this.Operators = new HashSet<Operator>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string WorkTime { get; set; }
        public string GMapId { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operator> Operators { get; set; }
    }
}
