//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRate
    {
        public int Id { get; set; }
        public string CurrencyName { get; set; }
        public double Sale { get; set; }
        public double Buy { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Bank Bank { get; set; }
    }
}
