//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Text { get; set; }
        public System.DateTime SendingTime { get; set; }
        public bool Sended { get; set; }
        public override string ToString() {
           return Header;
        }
    
        public virtual Receiver Receiver { get; set; }
    }
}
