//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetAdressServer
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Street
    {
        public int Id { get; set; }
        public string Adress { get; set; }
        public string Index { get; set; }
    }
}
